services:
  - type: web
    name: jancommerce
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi_production:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /
    branch: main
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.base
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: RENDER
        value: "true"
    databases:
      - name: jancommerce-db
        plan: free
        databaseName: jancommerce
        user: jancommerce

databases:
  - name: jancommerce-db
    plan: free
    databaseName: jancommerce
    user: jancommerce
